project:
  type: book
  output-dir: docs

book:
  title: "Python Data Science"
  reader-mode: true
  
  page-footer:
    left: |
      笔记由王安林创建。
    right: |
      根据<a href="https://quarto.org/">Quarto</a>建立.

  site-url: https://wanganlin00.github.io/DataScience/
  repo-url: https://github.com/Wanganlin00/DataScience/
  repo-branch: main
  repo-actions: [edit,issue]
  
  chapters:
    - index.qmd
    - preface.qmd
    
    - part: "R <---> Python"
      chapters: 
        - R-Python.qmd
        
    - part: "Python"
      chapters: 
        - basic_data_type.qmd
        - list.qmd
        - dictionary.qmd
        - control_structure.qmd
        - function.qmd
        - class.qmd
        - I-O.qmd
        - pandas.qmd
        - numpy.qmd
    
#pip install jupyter-cache

execute:
  cache: true
  error: true
  message: FALSE
  warning: false
  
toc: true
toc-expand: true
toc-depth: 4
toc-location: right
number-sections: true
number-depth: 4

knitr:
  opts_chunk: 
    comment: "###>" 
    collapse: TRUE
    
crossref: 
  fig-title: 图
  fig-prefix: 图
  tbl-title: 表
  tbl-prefix: 表
  
format: 
  html: 
    theme: cosmo
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: katex
#  pdf: 
#    documentclass: scrreprt
    

editor: visual

